################################################################################################################################################
# Fortify lets you build secure software fast with an appsec platform that automates testing throughout the DevSecOps pipeline. Fortify static,#
# dynamic, interactive, and runtime security testing is available on premises or as a service. To learn more about Fortify, start a free trial #
# or contact our sales team, visit microfocus.com/appsecurity.                                                                                 #
#                                                                                                                                              #
# Use this workflow template as a basis for integrating Fortify on Demand Static Application Security Testing(SAST) into your GitHub workflows.#
# This template demonstrates the steps to prepare the code+dependencies, initiate a scan, download results once complete and import into       #
# GitHub Security Code Scanning Alerts. Existing customers should review inputs and environment variables below to configure scanning against  #
# an existing application in your Fortify on Demand tenant. Additional information is available in the comments throughout the workflow, the   #
# documentation for the Fortify actions used, and the Fortify on Demand / ScanCentral Client product documentation. If you need additional     #
# assistance with configuration, feel free to create a help ticket in the Fortify on Demand portal.                                            #
################################################################################################################################################

name: Fortify Secret Scanning

on:
  workflow_dispatch:
    branches: [ "secret-scanning" ]
  pull_request:
    branches: [ "secret-scanning" ]
  push:
    branches: [ "secret-scanning" ]

jobs:
  Fortify-Secret-Scanning:

    runs-on: self-hosted
    container:
      image: fortifydocker/fortify-ci-tools
    permissions:
      actions: read
      contents: read
      security-events: write


    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Create Application Version
        run: |
          fcli ssc session login --url ${{ secrets.FTFY_SSC_BASE_URL }} --token ${{ secrets.FTFY_CI_TOKEN_DEC }}
          fcli ssc appversion create $GITHUB_REPOSITORY:${{ steps.extract_branch.outputs.branch }} --from $GITHUB_REPOSITORY:main --skip-if-exists --auto-required-attrs --issue-template "Prioritized High Risk Issue Template"

#      - name: Secrets Scanning
#        run: |
#          fcli sc-sast session login --ssc-url ${{ secrets.FTFY_SSC_BASE_URL }} -t ${{ secrets.FTFY_CI_TOKEN_DEC }} -c  ${{ secrets.FTFY_SAST_CLIENT_TOKEN }}
#          fcli tool scancentral-client install -t ${{ secrets.FTFY_SAST_CLIENT_TOKEN }} -u all -y --store scancentral
#          alias scancentral=$(fcli util var contents scancentral -o expr="{globalBinDir}")/scancentral
#          output=$(scancentral --sscurl ${{ secrets.FTFY_SSC_BASE_URL }} --ssctoken ${{ secrets.FTFY_CI_TOKEN_DEC }} start \
#          -bt mvn -bc "package --quiet" -application $GITHUB_REPOSITORY -version ${{ steps.extract_branch.outputs.branch }} \
#          -sargs "-analyzers configuration" -upload -uptoken ${{ secrets.FTFY_CI_TOKEN_DEC }})
#          jobToken=$(echo $output  | sed -n 's/.*Submitted job and received token: //p')
#          echo "Scan Job Token: $jobToken"
#          fcli sc-sast scan wait-for $jobToken

      - name: Export SSC vulnerability data to GitHub
        uses: fortify/github-action/ssc-export@v1
        env:
          SSC_URL: ${{secrets.FTFY_SSC_BASE_URL}}
          SSC_TOKEN: ${{secrets.FTFY_CI_TOKEN_DEC}}
          SSC_APPVERSION: alex-gendry/IWA-Java:secret-scanning

      - name: Security Gate
        run: if [ "$(fcli ssc pi get Issues --av $GITHUB_REPOSITORY:${{ steps.extract_branch.outputs.branch }} -o expr={value})" != "0.0" ]; then echo "::warning ::Security Gate Failure"; else echo Passed; fi

