name: Fortify on Demand SAST Scan (GHA)
on:
  workflow_dispatch:
  push:
  pull_request:
  

jobs:
  FOD-SAST:
    runs-on: self-hosted
    container:
      image: fortifydocker/fortify-ci-tools
    
    steps:    
      - name: Check out source code
        uses: actions/checkout@v4  
      - name: Run FoD SAST Scan
        uses: fortify/github-action/fod-sast-scan@v1
        env:
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{secrets.FOD_TENANT}}
          FOD_USER: ${{secrets.FOD_USER}}
          FOD_PASSWORD: ${{secrets.FOD_PAT}}
          # EXTRA_FOD_LOGIN_OPTS: --socket-timeout=60s
          FOD_RELEASE: '${{ github.event.repository.name }} [AG]:${{ github.ref_name }}'
          EXTRA_PACKAGE_OPTS: -oss
          DO_WAIT: true
          # DO_EXPORT: true



  
    # Create Application Release


    ### Package Creation
   # - mkdir $PACKAGE_FOLDER
    #- mkdir -p $PACKAGE_FOLDER/Src
    #- mkdir -p $PACKAGE_FOLDER/Libs $PACKAGE_FOLDER/Src
    # Debricked
    # mvn dependency:tree -DoutputFile=.debricked-maven-dependencies.tgf -DoutputType=tgf
    # cp -r .debricked-maven-dependencies.tgf $PACKAGE_FOLDER
    # Libs
    #- mvn dependency:copy-dependencies -DoutputDirectory=$PACKAGE_FOLDER/Libs
    # Sources
    #- cp -r src/* $PACKAGE_FOLDER/Src
    # WAR
    #- mvn package
    #- cp target/petclinic.war $PACKAGE_FOLDER

    #- cd $PACKAGE_FOLDER
    #- zip -r ../package.zip .
    #- cd ..

    # Upload
    #- fcli fod sast setup "$CI_PROJECT_TITLE":$CI_COMMIT_BRANCH --assessment Static --frequency Subscription --audit-preference Automated --technology-stack JAVA/J2EE/Kotlin --language-level 1.8 --oss --store sast_config
    #- fcli fod sast start "$CI_PROJECT_TITLE":$CI_COMMIT_BRANCH --purchase-entitlement  --in-progress Queue -f package.zip --store '?'
    #- sleep 10
    #- fcli fod sast wait-for '?'  -i 30s
